/* eslint-disable */
// Generated by plugins/i18n. Do not edit this file.
import 'vue-i18n'

type Simplify<T> = {
  [K in keyof T]: T[K]
}

type IsPlainObject<T> = T extends (...args: never[]) => unknown
  ? false
  : T extends readonly unknown[]
    ? false
    : T extends object
      ? true
      : false

type DeepMerge<A, B> =
  IsPlainObject<A> extends true
    ? IsPlainObject<B> extends true
      ? Simplify<{
          [K in keyof A | keyof B]:
            K extends keyof B
              ? K extends keyof A
                ? DeepMerge<A[K], B[K]>
                : B[K]
              : K extends keyof A
                ? A[K]
                : never
        }>
      : B
    : B

type MergeAll<T extends readonly unknown[], Acc = {}> = T extends readonly [
  infer Head,
  ...infer Tail,
]
  ? MergeAll<Tail, DeepMerge<Acc, Head>>
  : Acc

type IsEqual<A, B> =
  (<T>() => T extends A ? 1 : 2) extends <T>() => T extends B ? 1 : 2 ? true : false

type AssertTrue<T extends true> = T

type LocaleNodeEnUS0 = {
  antd: typeof import('../src/locales/en-US/antd').default
}

type LocaleNodeEnUS1 = {
  error: typeof import('../src/pages/error/locales/en-US').default
}

type LocaleNodeEnUS2 = {
  workspace: {
    overview: typeof import('../src/locales/en-US/workspace/overview').default
  }
}

type LocaleNodeZhCN0 = {
  antd: typeof import('../src/locales/zh-CN/antd').default
}

type LocaleNodeZhCN1 = {
  error: typeof import('../src/pages/error/locales/zh-CN').default
}

type LocaleNodeZhCN2 = {
  workspace: {
    overview: typeof import('../src/locales/zh-CN/workspace/overview').default
  }
}

type LocaleSchemaEnUS = MergeAll<[LocaleNodeEnUS0, LocaleNodeEnUS1, LocaleNodeEnUS2]>

type LocaleSchemaZhCN = MergeAll<[LocaleNodeZhCN0, LocaleNodeZhCN1, LocaleNodeZhCN2]>

type _LocaleSchemaCheckEnUS = AssertTrue<IsEqual<LocaleSchemaZhCN, LocaleSchemaEnUS>>

export type GeneratedI18nSchema = LocaleSchemaZhCN

declare module 'vue-i18n' {
  export interface DefineLocaleMessage extends LocaleSchemaZhCN {}
}

export {}
