// Generated by scripts/gen-per-type.ts. Do not edit by hand.

declare global {
  type KnownPerCodeType = 'system:user:create' | 'system:user:remove' | 'system:user:update'
  type PerCodeType = KnownPerCodeType | (string & {})
}

export type KnownPerCodeType = globalThis.KnownPerCodeType
export type PerCodeType = globalThis.PerCodeType
