/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/admin/': RouteRecordInfo<
      '/admin/',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/system/dict/': RouteRecordInfo<
      '/admin/system/dict/',
      '/admin/system/dict',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/system/menu/': RouteRecordInfo<
      '/admin/system/menu/',
      '/admin/system/menu',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/test/test': RouteRecordInfo<
      '/admin/test/test',
      '/admin/test/test',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/workspace/dashboard/': RouteRecordInfo<
      '/admin/workspace/dashboard/',
      '/admin/workspace/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin/workspace/overview/': RouteRecordInfo<
      '/admin/workspace/overview/',
      '/admin/workspace/overview',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/home/': RouteRecordInfo<
      '/home/',
      '/home',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login/': RouteRecordInfo<
      '/login/',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/request/': RouteRecordInfo<
      '/request/',
      '/request',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test/[form]/': RouteRecordInfo<
      '/test/[form]/',
      '/test/:form',
      { form: ParamValue<true> },
      { form: ParamValue<false> },
      | never
    >,
    '/test/[form]/[id]': RouteRecordInfo<
      '/test/[form]/[id]',
      '/test/:form/:id',
      { form: ParamValue<true>, id: ParamValue<true> },
      { form: ParamValue<false>, id: ParamValue<false> },
      | never
    >,
    'UserPage': RouteRecordInfo<
      'UserPage',
      '/user',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'apps/admin/pages/index.vue': {
      routes:
        | '/admin/'
      views:
        | never
    }
    'apps/admin/pages/system/dict/index.vue': {
      routes:
        | '/admin/system/dict/'
      views:
        | never
    }
    'apps/admin/pages/system/menu/index.vue': {
      routes:
        | '/admin/system/menu/'
      views:
        | never
    }
    'apps/admin/pages/test/test.vue': {
      routes:
        | '/admin/test/test'
      views:
        | never
    }
    'apps/admin/pages/workspace/dashboard/index.vue': {
      routes:
        | '/admin/workspace/dashboard/'
      views:
        | never
    }
    'apps/admin/pages/workspace/overview/index.vue': {
      routes:
        | '/admin/workspace/overview/'
      views:
        | never
    }
    'src/pages/home/index.vue': {
      routes:
        | '/home/'
      views:
        | never
    }
    'src/pages/login/index.vue': {
      routes:
        | '/login/'
      views:
        | never
    }
    'src/pages/request/index.vue': {
      routes:
        | '/request/'
      views:
        | never
    }
    'src/pages/test/[form]/index.vue': {
      routes:
        | '/test/[form]/'
      views:
        | never
    }
    'src/pages/test/[form]/[id].vue': {
      routes:
        | '/test/[form]/[id]'
      views:
        | never
    }
    'src/pages/user/index.vue': {
      routes:
        | 'UserPage'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
