import { existsSync, globSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'

import type { ResolvedLayoutPluginOptions } from './types'

import { LAYOUT_TYPES_DTS_PATH } from './constants'
import { normalizeExcludeGlob, normalizeFsPath } from './utils'

function normalizeLayoutDir(layoutDir: string) {
  return normalizeFsPath(layoutDir)
    .replace(/^\.?\//, '')
    .replace(/\/+$/, '')
}

function normalizeLayoutPath(value: string) {
  return value.replace(/\.vue$/, '').replace(/\/index$/, '')
}

function getModuleName(routePrefix: string, options: ResolvedLayoutPluginOptions) {
  const configuredModuleName = options.modules[routePrefix]?.module
  if (typeof configuredModuleName === 'string' && configuredModuleName.length > 0)
    return configuredModuleName

  return routePrefix
}

function resolveLayoutKey(filePath: string, options: ResolvedLayoutPluginOptions) {
  const normalizedPath = normalizeFsPath(filePath)
  const absolutePath = normalizedPath.startsWith('/') ? normalizedPath : `/${normalizedPath}`

  for (const source of options.layoutSources) {
    const layoutDir = normalizeFsPath(source.layoutDir).replace(/^\/+/, '').replace(/\/+$/, '')
    const prefix = `${layoutDir}/`

    if (source.kind === 'global') {
      if (!normalizedPath.startsWith(prefix)) continue
      return normalizeLayoutPath(normalizedPath.slice(prefix.length))
    }

    if (source.kind === 'module-static') {
      if (!normalizedPath.startsWith(prefix)) continue

      const routePrefix = source.routePrefix
      if (!routePrefix) continue

      const moduleName = getModuleName(routePrefix, options)
      return `${moduleName}/${normalizeLayoutPath(normalizedPath.slice(prefix.length))}`
    }

    if (source.kind === 'module-wildcard' && source.wildcardRegex) {
      const matched = absolutePath.match(new RegExp(source.wildcardRegex))
      if (!matched) continue

      const routePrefix = matched[1]
      const moduleName = getModuleName(routePrefix, options)
      return `${moduleName}/${normalizeLayoutPath(matched[2])}`
    }
  }

  return null
}

function toLayoutTypeLiteral(layoutName: string) {
  return `'${layoutName.replaceAll("'", "\\'")}'`
}

function createGeneratedDts(layoutNames: string[]) {
  if (layoutNames.length === 0) {
    return `/* eslint-disable */
// Generated by plugins/layout. Do not edit this file.
export type GeneratedLayoutType = never
`
  }

  const literals = layoutNames.map(toLayoutTypeLiteral).join('\n  | ')

  return `/* eslint-disable */
// Generated by plugins/layout. Do not edit this file.
export type GeneratedLayoutType =
  | ${literals}
`
}

export function generateLayoutTypeDts(root: string, options: ResolvedLayoutPluginOptions) {
  const layoutNames = new Set<string>([options.defaultLayout])
  if (typeof options.globalFallbackLayout === 'string' && options.globalFallbackLayout.length > 0)
    layoutNames.add(options.globalFallbackLayout)

  Object.values(options.modules).forEach((moduleOptions) => {
    if (typeof moduleOptions.layout === 'string' && moduleOptions.layout.length > 0)
      layoutNames.add(moduleOptions.layout)

    if (typeof moduleOptions.fallbackLayout === 'string' && moduleOptions.fallbackLayout.length > 0)
      layoutNames.add(moduleOptions.fallbackLayout)
  })

  const exclude = options.exclude.map((pattern) => {
    return normalizeExcludeGlob(pattern).replace(/^\/+/, '')
  })

  for (const layoutDir of options.layoutDirs) {
    const globPattern = `${normalizeLayoutDir(layoutDir)}/**/*.vue`
    const files = globSync(globPattern, {
      cwd: root,
      exclude,
    })

    for (const filePath of files) {
      const key = resolveLayoutKey(filePath, options)
      if (key) layoutNames.add(key)
    }
  }

  const sortedLayoutNames = [...layoutNames].sort((a, b) => a.localeCompare(b))
  const nextContent = createGeneratedDts(sortedLayoutNames)
  const outputPath = `${root}/${LAYOUT_TYPES_DTS_PATH}`

  mkdirSync(dirname(outputPath), { recursive: true })

  if (existsSync(outputPath)) {
    const currentContent = readFileSync(outputPath, 'utf8')
    if (currentContent === nextContent) return
  }

  writeFileSync(outputPath, nextContent, 'utf8')
}
