import type { ResolvedLayoutPluginOptions } from './types'
import { existsSync, globSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'
import { LAYOUT_TYPES_DTS_PATH } from './constants'
import { normalizeExcludeGlob, normalizeFsPath } from './utils'

function normalizeLayoutDir(layoutDir: string) {
  return normalizeFsPath(layoutDir).replace(/^\.?\//, '').replace(/\/+$/, '')
}

function resolveLayoutKey(filePath: string) {
  const normalizedPath = normalizeFsPath(filePath)
  const appLayout = normalizedPath.match(/^apps\/([^/]+)\/layouts\/(.+)\.vue$/)

  if (appLayout)
    return `${appLayout[1]}/${appLayout[2]}`.replace(/\/index$/, '')

  const srcLayout = normalizedPath.match(/^src\/layouts\/(.+)\.vue$/)
  if (srcLayout)
    return srcLayout[1].replace(/\/index$/, '')

  if (normalizedPath.startsWith('layouts/'))
    return normalizedPath.slice('layouts/'.length, -'.vue'.length).replace(/\/index$/, '')

  const layoutsIndex = normalizedPath.indexOf('/layouts/')
  if (layoutsIndex !== -1) {
    return normalizedPath
      .slice(layoutsIndex + '/layouts/'.length, -'.vue'.length)
      .replace(/\/index$/, '')
  }

  return null
}

function toLayoutTypeLiteral(layoutName: string) {
  return `'${layoutName.replaceAll('\'', '\\\'')}'`
}

function createGeneratedDts(layoutNames: string[]) {
  if (layoutNames.length === 0) {
    return `/* eslint-disable */
// Generated by plugins/layout. Do not edit this file.
export type GeneratedLayoutType = never
`
  }

  const literals = layoutNames
    .map(toLayoutTypeLiteral)
    .join('\n  | ')

  return `/* eslint-disable */
// Generated by plugins/layout. Do not edit this file.
export type GeneratedLayoutType =
  | ${literals}
`
}

export function generateLayoutTypeDts(
  root: string,
  options: ResolvedLayoutPluginOptions,
) {
  const layoutNames = new Set<string>([options.defaultLayout])
  const exclude = options.exclude.map((pattern) => {
    return normalizeExcludeGlob(pattern).replace(/^\/+/, '')
  })

  for (const layoutDir of options.layoutDirs) {
    const globPattern = `${normalizeLayoutDir(layoutDir)}/**/*.vue`
    const files = globSync(globPattern, {
      cwd: root,
      exclude,
    })

    for (const filePath of files) {
      const key = resolveLayoutKey(filePath)
      if (key)
        layoutNames.add(key)
    }
  }

  const sortedLayoutNames = [...layoutNames].sort((a, b) => a.localeCompare(b))
  const nextContent = createGeneratedDts(sortedLayoutNames)
  const outputPath = `${root}/${LAYOUT_TYPES_DTS_PATH}`

  mkdirSync(dirname(outputPath), { recursive: true })

  if (existsSync(outputPath)) {
    const currentContent = readFileSync(outputPath, 'utf8')
    if (currentContent === nextContent)
      return
  }

  writeFileSync(outputPath, nextContent, 'utf8')
}
