import { MENU_TYPE } from '../constants/menu.ts'

export interface PermissionLike {
  code?: string | null
  menuType?: string | null
  permission?: string | null
}

type PermissionSourceItem = string | PermissionLike | null | undefined

function resolvePermissionCode(item: PermissionSourceItem) {
  if (typeof item === 'string') {
    return item.trim() || undefined
  }

  const value = item?.permission ?? item?.code
  if (typeof value !== 'string') {
    return undefined
  }

  const normalized = value.trim()
  return normalized || undefined
}

function uniqueSorted(values: readonly string[]) {
  return [...new Set(values)].sort((left, right) => left.localeCompare(right))
}

export function extractPermissionCodes(items: readonly PermissionSourceItem[]) {
  return uniqueSorted(
    items.map(resolvePermissionCode).filter((code): code is string => Boolean(code)),
  )
}

export function extractMenuPermissions(items: readonly PermissionLike[]) {
  return extractPermissionCodes(items.filter(item => item.menuType === MENU_TYPE.BUTTON))
}

export function createPermissionTypeSource(codes: readonly string[]) {
  const normalizedCodes = uniqueSorted(codes)
  const knownType =
    normalizedCodes.length > 0
      ? normalizedCodes.map(code => `'${code.replace(/'/g, "\\'")}'`).join(' | ')
      : 'never'

  return `// Generated by scripts/gen-per-type.ts. Do not edit by hand.

declare global {
  type KnownPerCodeType = ${knownType}
  type PerCodeType = KnownPerCodeType | (string & {})
}

export type KnownPerCodeType = globalThis.KnownPerCodeType
export type PerCodeType = globalThis.PerCodeType
`
}
