import type { LocaleSource } from './scan'

function quote(value: string) {
  return JSON.stringify(value)
}

function sortByLocaleAndPath(left: LocaleSource, right: LocaleSource) {
  return (
    left.locale.localeCompare(right.locale) ||
    left.namespaceSegments.join('.').localeCompare(right.namespaceSegments.join('.')) ||
    left.filePath.localeCompare(right.filePath)
  )
}

function toLocaleGroups(sources: LocaleSource[]) {
  const groups = new Map<string, LocaleSource[]>()

  for (const source of [...sources].sort(sortByLocaleAndPath)) {
    const localeSources = groups.get(source.locale)
    if (localeSources) {
      localeSources.push(source)
      continue
    }
    groups.set(source.locale, [source])
  }

  return groups
}

export function createI18nRuntimeModuleCode(sources: LocaleSource[], defaultLocale: string) {
  const localeGroups = toLocaleGroups(sources)
  const defaultSources = localeGroups.get(defaultLocale) ?? []
  const lazyLocales = [...localeGroups.keys()].filter(locale => locale !== defaultLocale)

  const imports = defaultSources.map((source, index) => {
    return `import source${index} from ${quote(source.importPath)}`
  })

  const defaultRecords = defaultSources.map((source, index) => {
    return `  {
    namespace: [${source.namespaceSegments.map(quote).join(', ')}],
    value: source${index},
  }`
  })

  const loaders = lazyLocales
    .map(locale => {
      const localeSources = localeGroups.get(locale) ?? []
      const entries = localeSources
        .map(source => {
          return `    {
      namespace: [${source.namespaceSegments.map(quote).join(', ')}],
      load: () => import(${quote(source.importPath)}),
    }`
        })
        .join(',\n')

      return `  ${quote(locale)}: [
${entries}
  ]`
    })
    .join(',\n')

  return `/* eslint-disable */
// Generated by plugins/i18n. Do not edit this file.
${imports.join('\n')}

type LocaleRecord = {
  namespace: string[]
  value: Record<string, unknown>
}

type LocaleLoaderRecord = {
  namespace: string[]
  load: () => Promise<{ default: Record<string, unknown> }>
}

const defaultRecords: LocaleRecord[] = [
${defaultRecords.join(',\n')}
]

const loaders: Record<string, LocaleLoaderRecord[]> = {
${loaders}
}

const isPlainObject = (value: unknown): value is Record<string, unknown> => {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
}

const mergeMessageTrees = (
  left: Record<string, unknown>,
  right: Record<string, unknown>,
  pathSegments: string[] = [],
): Record<string, unknown> => {
  const result: Record<string, unknown> = { ...left }

  for (const [key, rightValue] of Object.entries(right)) {
    const nextPath = [...pathSegments, key]
    const leftValue = result[key]

    if (leftValue === undefined) {
      result[key] = rightValue
      continue
    }

    if (Array.isArray(leftValue) || Array.isArray(rightValue)) {
      throw new Error(\`[i18n] Array merge is not supported at "\${nextPath.join('.')}".\`)
    }

    if (isPlainObject(leftValue) && isPlainObject(rightValue)) {
      result[key] = mergeMessageTrees(leftValue, rightValue, nextPath)
      continue
    }

    throw new Error(\`[i18n] Duplicate locale message key "\${nextPath.join('.')}".\`)
  }

  return result
}

const wrapNamespace = (namespace: string[], value: Record<string, unknown>) => {
  if (namespace.length === 0) return value

  return namespace.reduceRight<Record<string, unknown>>((accumulator, segment) => {
    return {
      [segment]: accumulator,
    }
  }, value)
}

const buildMessages = (records: LocaleRecord[]) => {
  return records.reduce<Record<string, unknown>>((accumulator, record) => {
    return mergeMessageTrees(accumulator, wrapNamespace(record.namespace, record.value))
  }, {})
}

const defaultMessages = buildMessages(defaultRecords)
const loadedMessages = new Map<string, Record<string, unknown>>([
  [${quote(defaultLocale)}, defaultMessages],
])

const loadI18n = async (locale: string) => {
  if (loadedMessages.has(locale)) {
    return loadedMessages.get(locale)!
  }

  const localeLoaders = loaders[locale]
  if (!localeLoaders) {
    throw new Error(\`[i18n] Locale "\${locale}" is not configured.\`)
  }

  const records = await Promise.all(
    localeLoaders.map(async record => {
      const module = await record.load()
      return {
        namespace: record.namespace,
        value: module.default,
      }
    }),
  )

  const messages = buildMessages(records)
  loadedMessages.set(locale, messages)
  return messages
}

export { defaultMessages as messages, loadI18n }
export default defaultMessages
`
}
